---
title: "SankeyPlots"
output: html_document
---

```{r Load packages}
library(rCharts)
library(googleVis)
library(dplyr)
```

```{r Load & fix data}
# budget
rozp <- read.csv('./data-input/RozpoctovaRegulace.csv')
colnames(rozp) <- c('source','target','value')
rozp2 <- rozp
# rozp <- group_by(rozp, source) %.%
#   mutate(value_source = sum(value),
#          newsource = paste0(source, ', ', round(value_source,0))) %.%
#   ungroup() %.%
#   group_by(target) %.%
#   mutate(value_target = value,
#          newtarget = paste0(target, ', ', round(value_target,0)))
# 
# rozp2 <- rozp[c(5,7,3)]
# colnames(rozp2) <- c('source','target','value')

# public sector
vs <- read.csv('./data-input/VerejnySektor.csv')
colnames(vs) <- c('source','target','value')
vs2 <- vs
# vs <- group_by(vs, source) %.%
#   mutate(value_source = sum(value),
#          newsource = paste0(source, ', ', round(value_source,0))) %.%
#   ungroup() %.%
#   group_by(target) %.%
#   mutate(value_target = value,
#          newtarget = paste0(target, ', ', round(value_target,0)))
# 
# vs2 <- vs[c(5,7,3)]
# colnames(vs2) <- c('source','target','value')

```

```{r rChart Sankey Rozpocet}
sankeyPlotVS <- rCharts$new()
sankeyPlotVS$setLib('./src/rCharts_d3_sankey-gh-pages/')
sankeyPlotVS$setTemplate(script = "./src/rCharts_d3_sankey-gh-pages/layouts/chart_pb.html")

sankeyPlotVS$set(
  data = rozp2,
  nodeWidth = 15,
  nodePadding = 10,
  layout = 99,
  width = 750,
  height = 500,
  units = "tisíc"
)
 
sankeyPlotVS
sankeyPlotVS$print('blah', include_assets = TRUE, cdn=TRUE)
```

```{r rChart Sankey Verejny sektor}
sankeyPlotR <- rCharts$new()
sankeyPlotR$setLib('./src/rCharts_d3_sankey-gh-pages/')
sankeyPlotR$setTemplate(script = "./src/rCharts_d3_sankey-gh-pages/layouts/chart_pb.html")

sankeyPlotR$set(
  data = vs2,
  nodeWidth = 15,
  nodePadding = 10,
  layout = 99,
  width = 750,
  height = 500,
  units = 'tisíc'
)
 
sankeyPlotR
sankeyPlotR$print('blah', include_assets = TRUE, cdn=TRUE)
```

```{r Sankey Google Charts}
plot (
  gvisSankey(from = 'source',to = 'target', weight = 'value', data = rozp2,
             options = list(width=800))
  )
```